# Generated by Django 3.0.5 on 2020-04-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
