# Generated by Django 3.0.5 on 2020-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20200403_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='rating',
            field=models.BooleanField(),
        ),
    ]
