# Generated by Django 3.0.5 on 2020-04-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200403_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='rating',
            new_name='like',
        ),
    ]
